ToDoLead/ToDoApp/urls.py
from django.contrib import admin
from django.urls import path
from ToDoApp import views
from django.contrib.auth.views import LogoutView

app_name = 'ToDoApp'

urlpatterns = [
    path('login/', views.IniciodeSesion.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='ToDoApp:login'), name='logout'),
    path('registro_usuario/', views.RegistrodeUsuario.as_view(), name='registro_usuario'),

    path('', views.ListadeTareas.as_view(), name='tarea'),
    path('tarea/<int:pk>/', views.DetalledeTarea.as_view(), name='Detalles'),
    path('crear_tarea/', views.CrearTarea.as_view(), name='crear_tarea'),
    path('actualizar_tarea/<int:pk>/', views.ActualizarTarea.as_view(), name='actualizar_tarea'),
    path('borrar_tarea/<int:pk>/', views.BorrarTarea.as_view(), name='borrar_tarea'),
]

ToDoLead/ToDoLead/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDoApp.urls')),
]

ToDoLead/ToDoApp/models.py
from django.db import models
from django.contrib.auth.models import User


class Tarea(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    titulo = models.CharField(max_length=200, null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    completado = models.BooleanField(default=False)
    creado_en = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo
    
    class Meta:
        ordering = ['completado']

ToDoLead/ToDoApp/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView, FormView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .models import Tarea

from django.urls import reverse_lazy


class IniciodeSesion(LoginView):
    template_name = 'ToDoApp/Login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('ToDoApp:tarea')
    
class RegistrodeUsuario(FormView):
    template_name = 'ToDoApp/Registro_Usuario.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('ToDoApp:tarea')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegistrodeUsuario, self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('ToDoApp:tarea')
        return super(RegistrodeUsuario, self).get(*args, **kwargs)
   
class ListadeTareas(LoginRequiredMixin, ListView):
    model = Tarea
    context_object_name = 'tareas'
    template_name = 'ToDoApp/Lista_Tareas.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tareas'] = context['tareas'].filter(user=self.request.user)
        context['conteo'] = context['tareas'].filter(completado=False).count()

        search_input = self.request.GET.get('barra_busqueda') or ''
        if search_input:
            context['tareas'] = context['tareas'].filter(titulo__icontains=search_input)
        
        context['search_input'] = search_input
        return context
                                 
class DetalledeTarea(LoginRequiredMixin, DetailView):
    model = Tarea
    context_object_name = 'tareas'
    template_name = 'ToDoApp/Tarea.html'

class CrearTarea(LoginRequiredMixin, CreateView):
    model = Tarea
    fields = ['titulo', 'descripcion', 'completado']
    success_url = reverse_lazy('ToDoApp:tarea')
    template_name = 'ToDoApp/Crear_Tarea.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CrearTarea, self).form_valid(form)

class ActualizarTarea(LoginRequiredMixin, UpdateView):
    model = Tarea
    fields = ['titulo', 'descripcion', 'completado']
    success_url = reverse_lazy('ToDoApp:tarea')
    template_name = 'ToDoApp/Crear_Tarea.html'

class BorrarTarea(LoginRequiredMixin, DeleteView):
    model = Tarea
    context_object_name = 'tareas'
    success_url = reverse_lazy('ToDoApp:tarea')
    template_name = 'ToDoApp/Confirmacion_Borrar.html'
    

ToDoLead/ToDoApp/templates/ToDoApp/Confirmacion_Borrar.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'ToDoApp:tarea' %}">&#8592; Volver a la Lista de Tareas</a>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <p>¿Estás segúro de eliminar la tarea "{{tareas}}"? </p>
        <input class="button" type="submit" value="Borrar" />
    </form>
</div>

{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/Crear_Tarea.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<div class="header-bar">
    <a href="{% url 'ToDoApp:tarea' %}">&#8592; Volver a la Lista de Tareas</a>
</div>

<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Crear Tarea">
    </form>
</div>

{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/Lista_Tareas.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<div class="header-bar">
    <div>
        <h1>Bienvenid@ {{request.user|title}}</h1>
        <h3 style="margin:0">Tienes <i>{{conteo}}</i> Tareas por cumplir!</h3>
    </div>

    {% if request.user.is_authenticated %}
    <a href="{% url 'ToDoApp:logout' %}">Cerrar Sesión</a>
    {% else %}
    <a href="{% url 'ToDoApp:login' %}">Iniciar Sesión</a>
    {% endif %}

</div>

<div id="search-add-wrapper">
    <form method="GET" style="margin-top: 20px;display: flex;">
        <input type="text" name="barra_busqueda" value="{{search_input}}" placeholder="Buscar tarea...">
        <input class="button" type="submit" value="Buscar">
    </form>
    <a id="add-link" href="{% url 'ToDoApp:crear_tarea' %}">&#x2b;</a>
</div>

<div class="task-item-wrapper">
    {% for tareas in tareas %}
        <div class="task-wrapper">
            {% if tareas.completado %}
            <div class="task-title">
                <div class="task-complete-icon"></div>
                <i><s><a href="{% url 'ToDoApp:actualizar_tarea' tareas.id %}">{{tareas}}</a></s></i>
            </div>
            <a class="delete-link" href="{% url 'ToDoApp:borrar_tarea' tareas.id %}">&#215;</a>
            {% else %}
            <div class="task-title">
                <div class="task-incomplete-icon"></div>
                <a href="{% url 'ToDoApp:actualizar_tarea' tareas.id %}">{{tareas}}</a>
            </div>
            <a class="delete-link" href="{% url 'ToDoApp:borrar_tarea' tareas.id %}">&#215;</a>
            {% endif %}
        </div>
    
    {% empty %}
    <h3>No tienes tareas registradas</h3>
    {% endfor %}

</div>

{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/Login.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Iniciar Sesion</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Iniciar Sesion" >
    </form>
    <p>¿No tienes una cuenta? <a href="{% url 'ToDoApp:registro_usuario' %}"> Crea Una!</a></p>
</div>

{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/Registro_Usuario.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<div class="header-bar">
    <h1>Registro de Usuario</h1>
</div>

<div class="card-body">
    <form method="POST">
        {% csrf_token %}
        <label>{{form.username.label}}</label>
        {{form.username}}

        <label>{{form.password1.label}}</label>
        {{form.password1}}

        <label>{{form.password2.label}}</label>
        {{form.password2}}
        <input style="margin-top:10px;" class="button" type="submit" value="Registrarse" >
    </form>
    <p>¿Ya tienes una cuenta? <a href="{% url 'ToDoApp:login' %}"> Inicia Sesion!</a></p>
</div>


{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/Tarea.html
{% extends 'ToDoApp/main.html' %}
{% block content %}

<h1>Tarea: {{tareas}}</h1>
<a href="{% url 'ToDoApp:actualizar_tarea' tareas.id %}">Actualizar</a>

{% endblock content %}

ToDoLead/ToDoApp/templates/ToDoApp/main.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE-edge">
        <title>ToDoLead</title>
        <meta name="description" content="">
        <meta name="viewpoint" content="width=device-width, initial-scale=1">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@1,300&display=swap" rel="stylesheet">

        <style>
            body {
                background-color:#FAFAFA;
                font-family: 'Merriweather Sans', sans-serif;
                padding-top: 50px;
            }

            h1,
            h2,
            h3,
            h4,
            h5,
            h6,
                {
                font-family: 'Raleway', sans-serif;    
            }

            a,
            p {
                color: #1b1b1b
            }

            .container {
                max-width: 550px;
                margin: auto;
                background-color: #fff;
                -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
                box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            }

            .header-bar {
                display: flex;
                justify-content: space-between;
                color: #fff;
                padding: 10px;
                border-radius: 5px 5px 0 0;
                background: linear-gradient(90deg, #f0b885 0%, #e77810 43%, #e77810 100%);
            }

            .header-bar a {
                color: rgb(247,247,247);
                text-decoration: none;
            }

            .task-wrapper {
                display: flex;
                align-items: center;
                justify-content: space-between;
                padding: 20px;
                background-color: #fff;
                border-top: 1px solid rgb(226, 226, 226);
            }

            .task-title {
                display: flex;
            }

            .task-title a {
                text-decoration: none;
                color: #4b5156;
                margin-left: 10px;
            }

            .task-complete-icon {
                height: 20px;
                width: 20px;
                background-color: rgb(105, 192, 105);
                border-radius: 50%;
            }

            .task-incomplete-icon {
                height: 20px;
                width: 20px;
                background-color: rgb(218, 218, 218);
                border-radius: 50%;
            }

            .delete-link {
                text-decoration: none;
                font-weight: 900;
                color: #cf4949;
                font-size: 22px;
                line-height: 0;
            }

            #search-add-wrapper {
                display: flex;
                justify-content: space-between;
                align-items: center;
                padding: 10px;
            }

            #add-link {
                color: #eb796f;
                text-decoration: none;
                font-size: 42px;
                text-shadow: 1px 1px #81413b;
            }

            input[type=text],
            input[type=password],
            textarea {
                border: 1px solid #e77810;
                border-radius: 5px;
                padding: 10px;
                width: 90%;
            }

            label {
                padding-top: 10px !important;
                display: block;
            }

            .button {
                border: 1px solid #e77810;
                background-color: #fafafa;
                color: #e77810;
                padding: 10px;
                font-size: 14px;
                border-radius: 5px;
                cursor: pointer;
                text-decoration: none;
            }

            .card-body {
                padding: 25px;
            }
        </style>
    </head>
    <body>

        <div class="container">
            {% block content %}

            {% endblock content %}
        </div>

    </body>
</html>